version: '3'
services:
  student_service:
    image: zengqhh/student_service_swagger_flask_mongodb_demo
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"

  mongo:
    restart: unless-stopped
    image: mongo:latest
    ports:
      - "27017:27017"